version: '3'
services:
  app:
    image: ghcr.io/terensis/eodal_basetiffs:latest
    volumes:
      - ./host_output:/app/container_output
    command:
      [
        "-a",
        "aoi/aoi.gpkg",
        "-o",
        "container_output",
        "-t",
        "7",
        "-p",
        "sentinel-2" # "-r"  # Set this flag if you want the s2 download to run through
      ]
    container_name: testrun
volumes:
  host_output:
